### ISSUE TITLE
Links 'assistir' e 'mais informações'

### ISSUE THREAD

**Issue by marcosvafilho** [vaniamesquita/clone-netflix#2]
Nos links abaixo as tags `<button>` foram fechadas fora do `<a>`, sem querer.

https://github.com/vaniamesquita/clone-netflix/blob/1b19b1a6286c1edbc4e8702013c2eb07aa22411c/index.html#L66-L70

O que aparentemente está fazendo o botão não ser clicável como um todo, apenas onde há texto.

Perdão pela intromissão, fiquei feliz de ver seu projeto e quis contribuir :)

**Comment by vaniamesquita** [comment]
maquinhoooooo :)
esse passou batido kkkk
obrigadaaaa! vou ajustar =)

e não foi intromissão não, fique a vontade sempre que quiser/puder para me dar dicas, sugestões, pontos a melhorar, etc etc etc rs
